### ISSUE TITLE
Explanation of Heroku

### ISSUE THREAD

**Issue by CopeSc** [AABoyles/WebMicrobeTrace#53]
If possible, could a concise explanation of what heroku is and what parts are online/offline be made? Most folks are going to associate an app on a Google Chrome tab as connected to the internet and uploading files means uploading to the internet.

A quick note in the help banner or on this Github page would go a long way toward easing that confusion.

**Comment by AABoyles** [comment]
So Heroku doeasn't actually have anything to do with the app, and a casual user of the app shouldn't ultimately know that it exists (let alone that they're using it). However, a little exposition on the offline/online nature of the app may be a good addition. I'll write a wiki page about it.

**Comment by AABoyles** [comment]
https://github.com/AABoyles/WebMicrobeTrace/wiki/Offline-Usage
