### ISSUE TITLE
Revert to link origin schema

### ISSUE THREAD

**Issue by ells** [AABoyles/WebMicrobeTrace#78]
If I upload a FASTA and an edge list, the default styling will alternate coloring when an edge appears in both data sets. 

If a user recolors edges according to a data-type, there seems to be no way to revert back to the original alternating color schema. 

Selecting 'origin' as the color-by option seems to produce many identical categories as shown in the attached image. 
![image](https://user-images.githubusercontent.com/1420108/44736637-b2cb2a00-aabd-11e8-9cad-44d22b48e856.png)

**Comment by AABoyles** [comment]
Whoops! Nice bug!

**Comment by AABoyles** [comment]
Fixed awhile ago, don't feel like finding the commit.
